### PR TITLE
Fix: Improved Readme

### LINKED ISSUE #12: Improve the README file
Recommend a quickstart section here and a link to the documentation page.

### PR DESCRIPTION
**Pull request by Syeda-Mal**
Fixes #12 

The Readme file has been improved. Now, it has a definite structure, and it's easier to navigate.

Required stuff has been added, including:
1.  Proper About/Introduction Section
2. Quick Start Section
3.  Feature Section
4. Contribution Section
5.  Details Section

### CODE REVIEW

**Comment by Syeda-Mal** [comment]
fixed #12, waiting for review.

**Comment by plaresmedima** [comment]
This looks nice. I was just thinking whether this should include a disclaimer that the package is under development. Much of what is said in the readme expresses a long term intention but at the moment there is almost no real functionality. Same for the webpages.

**Comment by Syeda-Mal** [comment]
@plaresmedima thank you for the feedback..I'll edit the fix accordingly with a disclaimer in the start saying "under production" so that the readme sections would be interpreted as future intentions

**Comment by LucyKershaw** [comment]
Thank you, this is great.  Could you please change the part that says 'for major changes, please open an issue' to something   like: 'the package is in the early stages of development - if you would like to help by adding functionality, please open an issue first so that we can discuss how best to do this'

Thanks again!

**Comment by Syeda-Mal** [comment]
@LucyKershaw Of course. Doing it right now.

**Review by LucyKershaw — APPROVED** [review]
This looks perfect, thank you

**Pull request merged**
