### PR TITLE
Added tofts model

### PR DESCRIPTION
**Pull request by stadmill**
Added source code for tofts modelling and example usage.

### CODE REVIEW

**Comment by plaresmedima** [comment]
Thank you for the commit Sirisha,

A few comments:

You exposed the function exp_conv to the user in __init__.py, but this is not described in the Lexicon so cannot be part of the package. Can you please remove it from the __init__ file?

tofts docstring - discretaisation method lists multiple options but onlu 2 are actually implemented

tofts test - this needs to be extended - especially make sure to test all options, eg. run it once with dsicretization=exp, run it once with the convolve, and check that the results are alomost the same (eg run at very small dt). Ypu can also check that the ration of areas for ca and ca approximately equals the MTT. Also the offset variable is not tested.

docs. I get a warning running the documentation:
C:\Users\steve\Dropbox\Software\QIB-Sheffield\pypi\docs\source\generated\examples\tissue\plot_dummy.rst: WARNING: document isn't included in any toctree

the new tofts function is not listed in the alhpabetical index in the reference guide

Example looks great

An a separate note, times are entered in sec and Ktrans in 1/min. Is that intentional? Could get quite tricky when mixing different units for the time.

**Comment by stadmill** [comment]
Corrected init.py, docstrings, tests, reference guide and docs - as above. 

Re comment on units of Ktrans - we used units as defined in the Lexicon, which uses /min for Ktrans and seconds for time. 

Following discussions with @LucyKershaw, I edited the default BAT=30 in the AIF definition as BAT=0. This way we can have an arterial delay time as one of the input arguments in the tissue models. Currently defaults to 30 sec. Can be one of the fitted parameters later on.

**Comment by plaresmedima** [comment]
Thanks for the commits @stadmill 

No need to create a new PR. Your commits continue to be added to the same PR until I merge it, after which it will be closed for further commits.

Check list for code revision of new functions (You can use this too before you make a PR):

1. Code design:

- Depending on the outcome of the unit discussion (see separate email thread) you may have to convert all inputs and outputs to SI units.
- A point on notation: tofts() has a parameter t_offset that is defined OSIPI code Q.PH1.007. The OSIPI notation is "Ta" so it's confusing that this is called "t_offset" in the code. We should use the same notation in the code as in the lexicon for all variables. I did not check the other notations.
- The Tofts model as defined in the Lexicon (M.IC1.004) does not not have a t_offset parameter so the version in the code should not have one either. I think this would be opening the door to all kinds of confusions. Anybody who wants to implement this can either put a plug flow model and Tofts model in series, or we can define a new model in the Lexicon ("Delayed Tofts model") and then add it to the package with a new name. 

2. Doc string:

- In the example, You are using numpy but not importing it.

3. Code review

- Check behaviours for special cases. You have divisions by Ktrans and ve so what happens if one or both are 0? Or what happens if someone feeds in negative values for Ktrans (this can happen by mistake but also when fitting without bounds)? Throw an exception or return a result anyway? Throw a warning? Return C(t)=0? What is the right way to handle this?
- The function allows for a time array with non-uniform values (different spacing between time points) but I think the results will be incorrect. If this function only works for uniformly sampled time points you need to make that very clear in the documentation, and make sure to throw an error if a user enters a t-array that is not uniform. A better solution would be to have dt (float, sampling interval) as an argument rather than a time array t.  

As a general note, people will not always use the code as intended, and in fact that will be very common, especially for new people. That is what a bug is. When they do you want to give them as much specific information as possible about what they are doing wrong. Debugging code can become very frustrating if you only ever get error messages that are generated deep down in subroutines of subpackages. For instance, if I set Ktrans=0 in the test script I get this error message:

  File "..\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

It is very hard from that to work our what I am doing wrong. If the function does not allow Ktrans=0, then you need to check for that at the beginning of the function:

if Ktrans==0:


4. Building sphinx docs: 

- works fine now, no warnings

5. Check documentation build: 

- examples: look great
- reference guide: looks great. 
- Doc string: See Also is not hyperlinked
- Doc string: does not render properly (needs a white line before >>>)

6. Testing: 

- very nice - tests run fine and are comprehensive of all functionality. Just make sure to also test behaviour in unexpected scenarios, once you have handled those in the code (see code review).

**Comment by stadmill** [comment]
Updated as per comments and other discussions. 

- Units: corrected to use lexicon units for input and output parameters.
- Handling specific use cases e.g. Ktrans <=0 or ve <=0: code continues processing anyway, returning ct = 0*ca, but issues UserWarning. 
- Handling non-uniform time spacing: code continues processing, but issues warning that time array may be resampled internally. Original time spacing is restored for output. 
- Added further testing for above changes. 

- AIF: removed dose input parameter as it is undefined in lexicon. Suggest dose correction is performed by user as a later step. 
- Tofts: following discussions with Lucy, retained optional parameters (Ta, discretization method) as it is more user-friendly than having separate functions for each option.

**Comment by plaresmedima** [comment]
Thanks @stadmill I think  the points have been made and we are down to design choices effectively so I will close this pull request with some final comments

- Looking at the code you have added quite a lot of new stuff (eg. convolution with non-uniform t). Is that in the library somewhere or did you build it from scracth? If it's from scratch is this still aligned with the aims? I thought this was about essentially transferring validated content from the library. In any case I would do extensive functional testing of new features - compare to analytical formulas, compare to exp convolution etc
- I did not test code coverage but if you install pytest-cov as well you can do this with 
pytest --cov=dcmri --cov-report term-missing
This will also list the lines that are not covered by your test.
- Not sure you need to throw up a warning with v=0 and Ktrans=0 as these are perfectly physical situations and will be very common in practice when fitting with bounds. There is nothing to warn people about.

**Comment by plaresmedima** [comment]
Merged this and made you Admin so you can take it from here.

Please feel free to remove me as Admin when you feel the time is right. I
will not play the role anymore and you do not want to have too many people
with Admin rights. Probably just you and Lucy. It also means I will not get
alerts with every change.

Good luck!
Steven

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by stadmill** [comment]
Thanks Steven.

The non-uniform t bit is snipped from Michael T's code. I haven't written
anything from scratch, so all good. But I agree we should be cautious - all
previous testing was done independently between the different modules, so
we don't really know how it will work when we put AIF, tofts etc in series.
One of our milestones for this roadmap is to implement this testing, so we
will get there.

Re warnings, you are right. They were supposed to be temporary, I shall
remove them.

**Pull request merged**
